name: 'tmp'
description: 'test docker'
inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    default: 'world'
outputs:
  time:
    description: 'time of day'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}


