on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push docker image
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build
        run: docker build -t tmp .
      - name: docker tag
        run: |
          docker tag tmp ${{ secrets.DOCKER_USERNAME}}/tmp:${{ github.sha }}
          docker tag tmp ${{ secrets.DOCKER_USERNAME}}/tmp:latest
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME}}/tmp:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME}}/tmp:latest

