on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push docker image
    steps:
      # https://github.com/jens-maus/RaspberryMatic/blob/d5044bef3307bc61166377c162569de1a61cf332/.github/workflows/ci.yml#L34-L40
      - name: clean
        run: |
          df -h
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - uses: actions/checkout@v2
      - name: docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker build
        run: docker build -t tmp .
      - name: docker tag
        run: |
          docker tag tmp ${{ secrets.DOCKER_USERNAME}}/tmp:${{ github.sha }}
          docker tag tmp ${{ secrets.DOCKER_USERNAME}}/tmp:latest
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME}}/tmp:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME}}/tmp:latest

  docker-pull:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/tmp:latest
          docker run ${{ secrets.DOCKER_USERNAME }}/tmp:latest ls -l
