on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push docker image
    steps:
      # https://github.community/t5/GitHub-Actions/BUG-Strange-quot-No-space-left-on-device-quot-IOExceptions-on/td-p/46101/page/2
      - name: clean
        run: |
          df -h
          sudo swapoff /swapfile 
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get remove -y php7*
          df -h
      - uses: actions/checkout@v2
      - name: docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker build
        run: docker build -t tmp .
      - name: docker tag
        run: |
          docker tag tmp ${{ secrets.DOCKER_USERNAME}}/tmp:${{ github.sha }}
          docker tag tmp ${{ secrets.DOCKER_USERNAME}}/tmp:latest
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME}}/tmp:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME}}/tmp:latest

  docker-pull:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/tmp:latest
          docker run ${{ secrets.DOCKER_USERNAME }}/tmp:latest ls -l
